function skillsMember() {
  return {
    skills: [
      { name: 'JavaScript', level: 5 },
      { name: 'HTML', level: 5 },
      { name: 'CSS', level: 5 },
      { name: 'Python', level: 4 },
      { name: 'Java', level: 3 },
      { name: 'C++', level: 3 },
      { name: 'C#', level: 3 },
      { name: 'SQL', level: 3 },
      { name: 'PHP', level: 3 },
      { name: 'Ruby', level: 2 },
      { name: 'Swift', level: 2 },
      { name: 'Objective-C', level: 2 },
      { name: 'R', level: 2 },
      { name: 'Scala', level: 2 },
      { name: 'Go', level: 2 },
      { name: 'Kotlin', level: 2 },
      { name: 'TypeScript', level: 2 },
      { name: 'Shell', level: 2 },
      { name: 'Perl', level: 2 },
      { name: 'Lua', level: 2 },
      { name: 'Rust', level: 2 },
      { name: 'Haskell', level: 2 },
      { name: 'Erlang', level: 2 },
      { name: 'Clojure', level: 2 },
      { name: 'Groovy', level: 2 },
      { name: 'Visual Basic', level: 2 },
      { name: 'Dart', level: 2 },
      { name: 'Assembly', level: 2 },
      { name: 'VHDL', level: 2 },
      { name: 'Verilog', level: 2 },
      { name: 'Matlab', level: 2 },
      { name: 'LabVIEW', level: 2 },
      { name: 'AutoLISP', level: 2 },
      { name: 'COBOL', level: 2 },
      { name: 'Fortran', level: 2 },
      { name: 'Ada', level: 2 },
      { name: 'Lisp', level: 2 },
      { name: 'Prolog', level: 2 },
      { name: 'F#', level   : 2 },
    ]
    }
}
